### PR TITLE
Size: support regex exclusions

### PR DESCRIPTION
**Pull request by srvaroa**
Signed-off-by: Galo Navarro <anglorvaroa@gmail.com>

### CODE REVIEW

**Comment by akutz** [comment]
Thanks @srvaroa , looks perfect! @dilyar85, thoughts? Since you implemented the labeler, do you think this will work for us to exclude the generated assets?

**Comment by dilyar85** [comment]
> Thanks @srvaroa , looks perfect! @dilyar85, thoughts? Since you implemented the labeler, do you think this will work for us to exclude the generated assets?

Looks good to me too. Thanks @srvaroa for adding this support :)

**Comment by srvaroa** [comment]
Thanks @dilyar85 & @akutz, I'll get this released then

**Comment by srvaroa** [comment]
Done in [v1.10.0](https://github.com/srvaroa/labeler/releases/tag/v1.10.0)

**Pull request merged**
