### PR TITLE
chore: fix tests by mocking out diff request

### PR DESCRIPTION
**Pull request by garethjevans**

### CODE REVIEW

**Comment by srvaroa** [comment]
This commit is contained in the other PR, right? I can merge both there if so

**Comment by garethjevans** [comment]
It may be work merging them separately, I'll rebase the other one after this one is merged as they are dependant on each other.

**Comment by srvaroa** [comment]
Sounds good, i think this branch got the same first 2 commits after pushing the fmt fix. 

image

e392918 is meant to be only in the other PR right?

**Comment by garethjevans** [comment]
@srvaroa, sorry about the delay.  I've fixed this one and I think its good to merge.  I'll take a look at rebasing the schedule PR next.

**Review by srvaroa — APPROVED** [review]
Thanks!

**Pull request merged**
