### PR TITLE
feat: Add new type condition

### PR DESCRIPTION
**Pull request by philippwaller**
By setting the type attribute in the label configuration, the user can specify whether a rule applies exclusively to Pull Requests (PRs) or Issues. This functionality increases the adaptability of this GitHub Action, allowing users to create more tailored labeling strategies that differentiate between PRs and Issues or apply universally to both.

### CODE REVIEW

**Comment by srvaroa** [comment]
Thanks @philippwaller ! There is a conflict after merging the other PR but otherwise it LGTM

**Comment by philippwaller** [comment]
Great, thank you for the quick processing @srvaroa!

**Review by srvaroa — APPROVED** [review]

**Comment by srvaroa** [comment]
image

This is new! (strange it doesn't show the actual conflicts)

I'll to get the branch sorted locally and might repush to get it in

**Comment by srvaroa** [comment]
Something must be going on due to the branch being in a fork. I have added the relevant commit straight to master, which generally makes GH recognize the change and close the PR as merged. But doesn't happen in this case.

I'll close, but your commit _is_ in master. Release coming out shortly.

**Comment by srvaroa** [comment]
https://github.com/srvaroa/labeler/releases/tag/v1.9.0

**Comment by srvaroa** [comment]
The Dockerfile @master now references v1.9.0

**Pull request closed without merging**
